name: Kubernetes e2e test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set execute permissions for scripts
        run: |
          chmod +x ./scripts/*.sh

      - name: Install k3s
        run: ./scripts/install-k3s.sh

      - name: Wait for k3s service to be running
        run: ./scripts/wait-for-k3s.sh

      - name: Wait for k3s node to be ready
        run: ./scripts/wait-for-node.sh

      - name: Deploy Microservice
        run: ./scripts/deploy-microservice.sh

      - name: Run Test
        run: ./scripts/test.sh
